FROM centos:7

RUN \
    yum -y install\
     httpd\
     php\
     php-cli\
     php-common\
     mod_ssl\
     openssl
RUN mkdir /var/www/html/uploads
COPY upload.php /var/www/html
COPY gallery.php /var/www/html

RUN echo "<?php phpinfo(); ?>" > /var/www/html/hola.php


COPY docker.crt /docker.crt

COPY docker.key /docker.key

EXPOSE 443

COPY ssl.conf /etc/httpd/conf.d/default.conf



CMD apachectl -DFOREGROUND

